version: 2
updates:
  - package-ecosystem: "github-actions"
    assignees:
      - cmahnke
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
        - '*'
  - package-ecosystem: "maven"
    assignees:
      - cmahnke
    directories:
      - "/"
      - "core/"
      - "cli/"
      - "jc2pa/"
    schedule:
      interval: "weekly"
    groups:
      java:
        patterns:
        - '*'
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/jc2pa/src/main/rust"
    schedule:
      interval: "weekly"
    groups:
      rust:
        patterns:
        - '*'
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      docker:
        patterns:
        - '*'
