FROM --platform=amd64 ubuntu:26.04

LABEL maintainer="cmahnke@gmail.com"
LABEL org.opencontainers.image.source="https://github.com/cmahnke/fliiifenleger"

WORKDIR /app

COPY pom.xml .
COPY core ./core
COPY cli ./cli
COPY jc2pa ./jc2pa

ENV JAVA_HOME=/opt/jdk \
    CARGO_HOME=/opt/cargo \
    RUSTUP_HOME=/opt/rustup \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/jdk/bin:/opt/cargo/bin

RUN apt-get update && \
    apt-get install -y maven wget build-essential binaryen && \
    wget https://github.com/libjxl/libjxl/releases/download/v0.11.1/jxl-debs-amd64-ubuntu-24.04-v0.11.1.tar.gz && \
    tar xzf jxl-debs-amd64-ubuntu-24.04-v0.11.1.tar.gz && \
    apt install -y -f ./libjxl_0.11.1_amd64.deb && \
    apt install -y -f ./jxl_0.11.1_amd64.deb && \
    apt install -y -f ./libjxl-dev_0.11.1_amd64.deb && \
    find /usr/lib -name libjxl.so -print -exec ln -s {} /usr/lib/libjxl.so \; && \
    wget "https://api.adoptium.net/v3/binary/latest/25/ga/linux/x64/jdk/hotspot/normal/eclipse" -O jdk.tar.gz && \
    tar xzf jdk.tar.gz && \
    mv jdk-25* /opt/jdk && \
    # Rust toolchain for the jc2pa WASM build (c2pa's MSRV exceeds the
    # rustc shipped in the Ubuntu repositories, so rustup manages it).
    wget -qO- https://sh.rustup.rs | sh -s -- -y \
        --profile minimal \
        --default-toolchain stable \
        --target wasm32-wasip1 && \
    mvn --batch-mode clean install && \
    rm *.deb *.ddeb *.tar.gz
    #mv cli/target/fliiifenleger-cli.jar . && \
    #rm -rf cli core pom.xml && \
    #apt-get purge -y --auto-remove maven
